### PR TITLE
Runs on macOS and Windows

### PR DESCRIPTION
**Pull request by marcuspoehls**

### CODE REVIEW

**Comment by DanMossa** [comment]
Would you mind if I helped with this PR?
@marcuspoehls

**Comment by marcuspoehls** [comment]
@DanMossa Hey Daniel, thank you for your help. I appreciate it!

Up to this point, I only tested whether GitHub Actions support Docker on all operating systems. Well, they don't. Docker actions are only available on Linux.

We need to run the MongoDB setup for each OS I guess.

I'm happy if you can help out with this PR.

**Comment by marcuspoehls** [comment]
@DanMossa Hey Daniel, did you have time to have a look at multi-OS support?

**Comment by gimperiale** [comment]
Hi, are there any updates on this?

**Comment by marcuspoehls** [comment]
@gimperiale I haven’t looked into this over the last months. Do you want to submit a PR?

**Pull request closed without merging**
